GET http://localhost:3001/produtos

###
POST http://localhost:3001/produtos
content-type: application/json

{
    "produto": "Notebook Samsumb",
    "descricao": "Notebook preto",
    "quantidade": 15
}

###
DELETE http://localhost:3001/produtos/33
content-type: application/json

{
    "produto": "Teclado Mecanico",
    "descricao": "Teclado Hyper-X Vermelho",
    "quantidade": 120
}
